services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    container_name: nul-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: packages/server/.env.prod

  bot:
    build:
      context: .
      dockerfile: packages/bot/Dockerfile
    container_name: nul-bot
    restart: unless-stopped
    env_file: packages/bot/.env.prod
    depends_on:
      - server

networks:
  default:
    name: nul-network
